Clean up bash script

diff --git a/.github/workflows/h5p-build.yml b/.github/workflows/h5p-build.yml
--- a/.github/workflows/h5p-build.yml
+++ b/.github/workflows/h5p-build.yml
@@ -21,16 +21,18 @@ jobs:
           node-version: '16'
 
       - name: Check translations with H5P-CLI
+        shell: bash
         run: |
           # Check for missing translation directory
-          if [ ! -d "./language" ]
-          then
+          if [ ! -d "./language" ]; then
             echo "No language directory found"
             exit 0
           fi
 
+          # Install H5P CLI tool
           npm i -g h5p
 
+          # Color palette
           COLOR_OFF='\033[0m'
           COLOR_RED='\033[0;31m'
           COLOR_BLUE='\033[0;34m'
@@ -40,36 +42,32 @@ jobs:
 
           # Check JSON validity
           check_json_validity() {
-            if ! cat $entry | json_pp &> /dev/null
-            then
+            if ! json_pp < "$entry" &> /dev/null; then
               echo "Translation file does not seem to be valid JSON"
-              cat $entry | json_pp || true
-              ((ERROR_COUNT=ERROR_COUNT+1))
-              continue
+              json_pp < "$entry" || true
+              (( ERROR_COUNT=ERROR_COUNT + 1 ))
             fi
           }
 
           # Check unsafe translations
           check_unsafe_translations() {
-            UNSAFE_TRANSLATIONS_COUNT=$(echo "$RESULT" | grep "^Unsafe translation$" | wc -l)
-            if (( UNSAFE_TRANSLATIONS_COUNT == 0 ))
-            then
+            UNSAFE_TRANSLATIONS_COUNT=$(echo "$RESULT" | grep -c "^Unsafe translation$")
+
+            if (( UNSAFE_TRANSLATIONS_COUNT == 0 )); then
               (( ERROR_COUNT=ERROR_COUNT + 1 ))
             else
               ISSUE_COUNT=$(echo "$RESULT" | wc -l)
               (( ISSUE_COUNT=(ISSUE_COUNT - 1) / 2 ))
-              if (( $ISSUE_COUNT - $EXPECTED_UNSAFE_TRANSLATIONS >= $UNSAFE_TRANSLATIONS_COUNT ))
-              then
+
+              if (( ISSUE_COUNT - EXPECTED_UNSAFE_TRANSLATIONS >= UNSAFE_TRANSLATIONS_COUNT )); then
                 (( ERROR_COUNT=ERROR_COUNT + 1 ))
               fi
             fi
           }
 
-          for entry in "./language"/*
-          do
-            BASENAME=$(basename $entry)
-            if [[ $BASENAME == "*" ]]
-            then
+          for entry in "./language"/*; do
+            BASENAME=$(basename "$entry")
+            if [[ $BASENAME == "*" ]]; then
               continue
             fi
 
@@ -80,26 +78,26 @@ jobs:
             cd ..
 
             # Check translation validity
-            LANGUAGE_CODE=$(basename $entry .json)
+            LANGUAGE_CODE=$(basename "$entry" .json)
 
-            RESULT=$(npx h5p check-translations -diff $LANGUAGE_CODE $LIBRARY_DIR)
+            RESULT=$(npx h5p check-translations -diff "$LANGUAGE_CODE" "$LIBRARY_DIR")
             echo "$RESULT"
-            if (( $(echo "$RESULT" | grep "FAILED" | wc -l) != 0 ))
-            then
+
+            if (( $(echo "$RESULT" | grep -c "FAILED") != 0 )); then
+              # ${{...}} will be replaced by github action
               EXPECTED_UNSAFE_TRANSLATIONS=${{ inputs.expected-unsafe-translations }}
-              if [[ $EXPECTED_UNSAFE_TRANSLATIONS ]]
-              then
+
+              if [[ $EXPECTED_UNSAFE_TRANSLATIONS ]]; then
                 check_unsafe_translations
               else
                 (( ERROR_COUNT=ERROR_COUNT + 1 ))
               fi
             fi
 
-            cd - > /dev/null
+            cd - > /dev/null || continue
           done
 
-          if (( $ERROR_COUNT != 0 ))
-          then
+          if (( ERROR_COUNT != 0 )); then
             echo -e "${COLOR_RED}Some translations seem to contain errors${COLOR_OFF}"
             exit 1
           else
