Add input for expected unsafe translations

diff --git a/.github/workflows/h5p-build.yml b/.github/workflows/h5p-build.yml
--- a/.github/workflows/h5p-build.yml
+++ b/.github/workflows/h5p-build.yml
@@ -2,6 +2,10 @@ name: Build H5P content type
 
 on:
   workflow_call:
+    inputs:
+      expected-unsafe-translations:
+        required: false
+        type: string
 
 jobs:
   build:
@@ -25,16 +29,43 @@ jobs:
             exit 0
           fi
 
-          # H5P CLI is being rewritten completely, so be cautios and pin version
-          npm i -g h5p@0.11.0 --save --save-exact
+          npm i -g h5p
 
           COLOR_OFF='\033[0m'
           COLOR_RED='\033[0;31m'
           COLOR_BLUE='\033[0;34m'
 
           ERROR_COUNT=0
-
           LIBRARY_DIR=$(pwd | rev | cut -d "/" -f1 | rev)
+
+          # Check JSON validity
+          check_json_validity() {
+            if ! cat $entry | json_pp &> /dev/null
+            then
+              echo "Translation file does not seem to be valid JSON"
+              cat $entry | json_pp || true
+              ((ERROR_COUNT=ERROR_COUNT+1))
+              continue
+            fi
+          }
+
+          # Check unsafe translations
+          check_unsafe_translations() {
+            UNSAFE_TRANSLATIONS_COUNT=$(echo "$RESULT" | grep "^Unsafe translation$" | wc -l)
+            if (( UNSAFE_TRANSLATIONS_COUNT == 0 ))
+            then
+              (( ERROR_COUNT=ERROR_COUNT + 1 ))
+            else
+              EXPECTED_UNSAFE_TRANSLATIONS=${{ inputs.expected-unsafe-translations }}
+
+              ISSUE_COUNT=$(echo "$RESULT" | wc -l)
+              (( ISSUE_COUNT=(ISSUE_COUNT - 1) / 2 ))
+              if (( $ISSUE_COUNT - $EXPECTED_UNSAFE_TRANSLATIONS >= $UNSAFE_TRANSLATIONS_COUNT ))
+              then
+                (( ERROR_COUNT=ERROR_COUNT + 1 ))
+              fi
+            fi
+          }
 
           for entry in "./language"/*
           do
@@ -46,30 +77,29 @@ jobs:
 
             echo -e "${COLOR_BLUE}Checking $BASENAME${COLOR_OFF}"
 
-            # Check JSON validity
-            if ! cat $entry | json_pp &> /dev/null
-            then
-              echo "Translation file does not seem to be valid JSON"
-              cat $entry | json_pp || true
-              ((ERROR_COUNT=ERROR_COUNT+1))
-              continue
-            fi
+            check_json_validity
 
             cd ..
 
             # Check translation validity
             LANGUAGE_CODE=$(basename $entry .json)
+
             RESULT=$(npx h5p check-translations -diff $LANGUAGE_CODE $LIBRARY_DIR)
             echo "$RESULT"
-            if [[ $(echo "$RESULT" | grep "FAILED" | wc -l) != "0" ]]
+            if (( $(echo "$RESULT" | grep "FAILED" | wc -l) != 0 ))
             then
-              ((ERROR_COUNT=ERROR_COUNT+1))
+              if [[ ${{ inputs.expected-unsafe-translations }} ]]
+              then
+                check_unsafe_translations
+              else
+                (( ERROR_COUNT=ERROR_COUNT + 1 ))
+              fi
             fi
 
             cd - > /dev/null
           done
 
-          if [[ $ERROR_COUNT != "0" ]]
+          if (( $ERROR_COUNT != 0 ))
           then
             echo -e "${COLOR_RED}Some translations seem to contain errors${COLOR_OFF}"
             exit 1
